### ISSUE TITLE
[Feature Requests] Visualize the location of marker entities

### ISSUE THREAD

**Issue by nea-c** [ToBinio/visible-entities#1]
To implement this functionality in a multiserver, it is necessary to send/receive “marker entity packets”.
However, I don't think Minecraft is designed to send/receive “marker entity packets”.

Assuming we use a server mod, is it possible to implement this functionality?

**Comment by ToBinio** [comment]
just published a new [version 0.1.2](https://modrinth.com/mod/visible-entities/version/0.1.2+mc1.21.0) which adds marker rendering.

Like you said it requires server support so it only works in singleplayer & when the mod is also installed on the server
