### ISSUE TITLE
[Feature Request] More fine-grained display and hide settings

### ISSUE THREAD

**Issue by KozukiYOMA** [ToBinio/visible-entities#2]
For example, I would like the ability to set that I am the only transparent entity that can be displayed, and the ability to fine-tune the entities that are displayed.

**Comment by ToBinio** [comment]
could you elaborate a bit more?
would you like to have a list of entities to configure that e.g. only parrots and chickens are rendered? 

In which way would you like to be the only transparent entity displayed? Only the player with your username?

**Comment by KozukiYOMA** [comment]
Only the player, or only me, or only zombies, etc.
What about having a blacklist that is not displayed and a whitelist that is displayed, where you can put the ID of the entity and set it to be displayed or not, or set the transparent player that is displayed to be only you?
My problem is that once all the transparent entities are displayed, the transparent player will also appear on the regular server and could be considered a cheat.

**Comment by ToBinio** [comment]
so an editable list in which you can define entity types (e.g chicken, zombie) and a special marker for "me"
that you can toggle to be a white or blacklist would work for your use case?

**Comment by KozukiYOMA** [comment]
Yes.

**Comment by ToBinio** [comment]
Perfect, I will properly work on this on coming weekend

**Comment by ToBinio** [comment]
just published a new version [0.1.3](https://modrinth.com/mod/visible-entities/versions) that contains the filter list.
let me know if you run into any issues!

and thanks for the suggestion

**Comment by KozukiYOMA** [comment]
thank you
