### ISSUE TITLE
[Suggestion] Function to be turned on by default

### ISSUE THREAD

**Issue by KozukiYOMA** [ToBinio/visible-entities#3]
I like this mod.
However, it is a bit tedious to activate it by pressing the toggle key every time I join a world or server, and sometimes I forget to do it.
I think if it could be enabled by default, I would not forget.
I suggest that we be able to toggle the default of enable/disable.
The default toggle I'm thinking of for enable/disable is like a button that toggles between enabled and disabled by default for FirstPersonModels, a mod that shows your skin as it would appear in third person view from first person view.

**Comment by ToBinio** [comment]
would it work for you simply storing the current enabled/ disabled state in the config file? 
so when you restart/ rejoin it simply uses the state it last was set on?

**Comment by KozukiYOMA** [comment]
Enable defaults are enabled even if you enter the world after rejoining or restarting,
If the default is disabled, then even if it is enabled after entering a world, it will be disabled after rejoining or restarting.
I hadn't thought of making the enable/disable setting carry over, but I think it's a good idea.
If you save the switch to your settings file, I believe you can take over the settings.

**Comment by ToBinio** [comment]
just published [0.1.4](https://modrinth.com/mod/visible-entities/versions) which includes that change

**Comment by KozukiYOMA** [comment]
thank you!!
